require("plugins")
require('options')
require('nvim-tree-config')
require("lualine-config")
require("bufferline-config")
require("treesitter-config")
require("autopairs-config")
require("keybindings")
vim.cmd('colorscheme nord')

